const mockMovies = [
  {
    id: 1,
    title: 'Test Movie 1',
    original_title: 'Test Movie 1',
    original_language: 'en',
    overview: 'Test overview for movie 1',
    poster_path: '/poster1.jpg',
    backdrop_path: '/backdrop1.jpg',
    genre_ids: [28, 12],
    release_date: '2024-01-01',
    vote_average: 8.5,
    vote_count: 1000,
    popularity: 100.5,
    adult: false,
    video: false,
  },
  {
    id: 2,
    title: 'Test Movie 2',
    original_title: 'Test Movie 2',
    original_language: 'en',
    overview: 'Test overview for movie 2',
    poster_path: '/poster2.jpg',
    backdrop_path: '/backdrop2.jpg',
    genre_ids: [35, 18],
    release_date: '2024-02-01',
    vote_average: 7.2,
    vote_count: 500,
    popularity: 85.3,
    adult: false,
    video: false,
  },
  {
    id: 3,
    title: 'Test Movie 3',
    original_title: 'Test Movie 3',
    original_language: 'uk',
    overview: 'Test overview for movie 3',
    poster_path: null,
    backdrop_path: '/backdrop3.jpg',
    genre_ids: [16, 10751],
    release_date: '2024-03-01',
    vote_average: 9.1,
    vote_count: 2000,
    popularity: 150.8,
    adult: false,
    video: false,
  },
];

export default mockMovies;
